<?php
/**
 * The template for displaying the navbar on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/navbar.scss.
 * The Navbar generated by PHP can be configured in functions.php.
 *
 * This is the template that displays all of the <head> section and everything up until the main body.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Mama_Llama
 * @since 1.0.0
 */

?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
    <!--Meta Info-->
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="profile" href="https://gmpg.org/xfn/11">

    <!--Font Awesome Loadin-->
    <script src="https://kit.fontawesome.com/e9f0a6af17.js" crossorigin="anonymous"></script>

    <!--Wordpress Required Stuff-->
    <?php wp_head(); ?>
</head>

<!--Open Body, Apply any Tailwind classes that are global here, Leave WP stuff alone. -->
<body class="leading-normal tracking-normal"
      style="font-family: 'Source Sans Pro', sans-serif;" <?php body_class(); ?>>
<?php wp_body_open(); ?>


<!--Start Navbar, and by that I mean the single logo -->
<div class="relative">
    <a href="/frontpage">
    <img class = "absolute w-20 inset-3" src="http://mothers-day-2022.local/wp-content/uploads/2022/04/FC_circle_white.png"
         alt="Foothills Logo">
    </a>
</div>
<!--Start Body-->







